[requirement.radio]
description = "These requirements targets the low level radio communication."

[requirement.radio.latency]
description = "Link round-trip latency for radio packets"
rational = "Empirical"
limit_high_ms = 8

[requirement.radio.bwsmall]
description = "Packet rate (packets per seconds) for small radio packets (4 bytes)"
rational = "Empirical"
background = """
This is what our test machine manages through Docker.
Which can be viewed as our lowest supported system.
"""
packet_size = 4
limit_low = 500

[requirement.radio.bwbig]
description = "Packet rate (packets per seconds) for big radio packet (28 bytes)"
rational = "Empirical"
background = """
This is what our test machine manages through Docker.
Which can be viewed as our lowest supported system.
"""
packet_size = 28
limit_low = 350

[requirement.radio.reliability]
description = "Packet exchange without any information loss"
rational = "Design"
background = """
We are pinging the Crazyflie with the max size packet and never loose any data
"""
limit_low = 1000
packet_size = 30
