name: Crazy Stab Lab experiment 🗡️

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      category:
        description: 'Test category.' #Format: tests/.../test_*.py'
      filter:
        description: 'Select a filter to filter the tests on' #NOTE to filter on more than one test, use the following syntax: -k "filter1 or filter2"
        default: ''
      devices:
        description: 'Devices to run the tests on.' #Format: <device1>,<device2>,...'

#  schedule:
#  - cron:  '0 6 * * *'

jobs:
  testsuite_at_crazylab:
    env:
      CRAZY_SITE: crazylab-malmö
      TEST_FILE: TestRun-${{github.run_number}}.xml
      CRAZY_DEVICE: ${{github.event.inputs.devices}}
    runs-on: self-hosted
    timeout-minutes: 120
    container:
      image: python:3.9.7-buster
      options: --privileged
    steps:
      - name: Install libusb
        run: |
          apt update
          apt install -y libusb-1.0-0 uhubctl

      - name: Upgrade pip
        run:  |
          pip3 install --upgrade pip

      - name: Install pytest
        run: pip3 install pytest

      - name: Install Crazyflie python library
        run: pip3 install git+https://github.com/bitcraze/crazyflie-lib-python.git@master

      - name: Check out sources
        uses: actions/checkout@v4

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Download latest firmware files
        with:
          repo: bitcraze/crazyflie-release
          workflow: nightly-experiment.yml
        uses: dawidd6/action-download-artifact@v3

      - name: Reset power to all devices
        run: python3 management/usb-power-reset.py -a reset

      - name: Upgrade devices to latest firmware
        run: python3 management/program.py --file nightly-experiment/firmware-cf2-nightly-experiment.zip

      - name: Run test suite
        
        run: pytest --verbose --junit-xml ${{env.TEST_FILE}} ${{github.event.inputs.category}} -k ${{github.event.inputs.filter}}

      - name: Upload test file
        uses: actions/upload-artifact@v4
        with:
          name: test_report
          path: ${{env.TEST_FILE}}

      - name: Pretty print test results
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: ${{env.TEST_FILE}}
          summary: true
          title: Test results
