name: Crazyswarm test 🐝

# Controls when the action will run.
on:
  push:
    branches:
      - main

jobs:
  cs2_at_crazylab:
    runs-on: self-hosted
    container:
      image: ros:humble
      options: --privileged

    env:
      CSW_PYTHON: python3
      CRAZYSWARM_PATH: crazyswarm
      CRAZYSWARM_YAML: crazylab-malmö.yaml

    steps:
      - name: Install Crazyswarm dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt install -y git swig libpython3-dev python3-numpy \
          python3-yaml python3-matplotlib python3-pytest python3-scipy \
          libpcl-dev libusb-1.0-0-dev sdcc gcc-arm-none-eabi \
          ros-humble-tf-tranformations
          python3-toml python3-pip
          pip3 install rowan cflib transforms3d

      - name: Install Crazyswarm2
        run: |  
          mkdir -p ros2_ws/src
          cd ros2_ws/src
          git clone https://github.com/IMRCLab/crazyswarm2.git --recursive
          git clone --branch ros2 --recursive https://github.com/IMRCLab/motion_capture_tracking.git

      - name: Build Crazyswarm2
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
        shell: bash

