name: Crazyswarm2 test 🐝

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  cs2_at_crazylab:
    runs-on: self-hosted
    container:
      image: ros:humble
      options: --privileged

    env:
      CSW_PYTHON: python3
      CRAZYSWARM_PATH: crazyswarm
      CRAZYSWARM_YAML: crazylab-malmö.yaml

    steps:
      - name: Check out sources
        uses: actions/checkout@v4
        
      - name: Install Crazyswarm dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt install -y git swig libpython3-dev python3-numpy \
          python3-yaml python3-matplotlib python3-pytest python3-scipy \
          libpcl-dev libusb-1.0-0-dev sdcc gcc-arm-none-eabi \
          curl python3-toml python3-pip
          pip3 install rowan cflib transforms3d ruamel.yaml
          DEBIAN_FRONTEND=noninteractive apt install -y ros-humble-motion-capture-tracking \
          ros-humble-joy 

      - name: Install Crazyswarm2
        run: |
          mkdir -p ros2_ws/src
          cd ros2_ws/src
          rm -rf crazyswarm2 motion_capture_tracking
          git clone https://github.com/IMRCLab/crazyswarm2.git --recursive
          git clone --branch ros2 --recursive https://github.com/IMRCLab/motion_capture_tracking.git

      - name: check folder Crazyswarm2
        run: |  
          cd ros2_ws/src/
      
      - name: Build Crazyswarm2
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          rm -rf install/ log/ build/
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Install Crazyflie python library
        run: pip3 install git+https://github.com/bitcraze/crazyflie-lib-python.git@master

      - name: Download latest firmware files
        with:
          repo: bitcraze/crazyflie-release
          workflow: nightly.yml
        uses: dawidd6/action-download-artifact@v2

      - name: Run Crazyswarm2 Server
        run: |
          source /opt/ros/humble/setup.bash
          source ros2_ws/install/setup.bash
          cd swarm/cs2-test-yamls/ && ros2 launch launch.py server_yaml_file:='cs2_server.yaml' & ros2 run crazyflie_examples set_param.py
        shell: bash




        

      

