name: crazyflie-lib - macOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  crazyflie_lib_macos:
    runs-on: [self-hosted, macOS]
    timeout-minutes: 120
    env:
      CRAZY_SITE: stablab-macos
    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Run test suite
        run: cargo test --manifest-path suites/crazyflie-lib/Cargo.toml -- --test-threads=1
