name: Crazy Stab Sanity 🗡️

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * 1-5'
jobs:
  #TODO add flashing of crazyflies
  setup_mac:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Check out sources
        uses: actions/checkout@v4
      - name: Download latest firmware files
        with:
          repo: bitcraze/crazyflie-release
          workflow: nightly.yml
          path: nightly
        uses: dawidd6/action-download-artifact@v4

  sanity_testsuite_on_mac:
    needs: [setup_mac]
    runs-on: [self-hosted, macOS]
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    env:
      TEST_FILE: Mac__sanity_test_job-${{github.run_number}}-${{ matrix.python_version }}
      CRAZY_SITE: crazylab-mac
      PYTHON_VERSION: ${{ matrix.python_version }}
    timeout-minutes: 120
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python_version }}

      - name: Install project dependencies
        run: uv sync --project suites/cflib2
      # - name: Upgrade devices to latest firmware
      #   run: uv run python management/program.py --file nightly/ --retries 3

      - name: Run test suite
        run: uv run --project suites/cflib2 pytest --verbose --html=${{env.TEST_FILE}}.html --junit-xml ${{env.TEST_FILE}}.xml -m sanity suites/cflib2

      - name: Upload test file
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.TEST_FILE}}_results
          if-no-files-found: warn
          path: |
            ${{env.TEST_FILE}}.html
            ${{env.TEST_FILE}}.xml
            assets/style.css
            suites/cflib2/uv.lock

      - name: Pretty print test results
        if: ${{ !cancelled() }}
        uses: pmeier/pytest-results-action@main
        with:
          path: ${{env.TEST_FILE}}.xml
          summary: true
          title: Test results

  sanity_testsuite_on_linux:
    if: ${{ !cancelled() }}
    runs-on: [self-hosted, linux]
    needs: [sanity_testsuite_on_mac]
    strategy:
      matrix:
        python_version: ["3.10", "3.11","3.12", "3.13"]
      fail-fast: false
    env:
      TEST_FILE: Linux_sanity_test_job-${{github.run_number}}-${{ matrix.python_version }}
      CRAZY_SITE: crazylab-malmö
      CRAZY_DEVICE: cf21_stock,cf21bl_stock
      PYTHON_VERSION: ${{ matrix.python_version }}
    timeout-minutes: 200
    container:
      image: python:${{ matrix.python_version }}-bookworm
      options: --privileged
    steps:
    - name: Check out sources
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt update
        apt install -y libusb-1.0-0 uhubctl

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Install project dependencies
      run: uv sync --project suites/cflib2
    # - name: Download latest firmware files
    #   with:
    #     repo: bitcraze/crazyflie-release
    #     workflow: nightly.yml
    #     path: nightly
    #   uses: dawidd6/action-download-artifact@v4

    - name: Reset power to all devices
      run: uv run --project suites/cflib2 python management/usb-power-reset.py -a reset

    # - name: Upgrade devices to latest firmware
    #   run: uv run python management/program.py --file nightly/ --retries 3

    - name: Run test suite
      run: uv run --project suites/cflib2 pytest --verbose --html=${{env.TEST_FILE}}.html --junit-xml ${{env.TEST_FILE}}.xml -m sanity suites/cflib2

    - name: Upload test file
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.TEST_FILE}}_results
        if-no-files-found: warn
        path: |
          ${{env.TEST_FILE}}.html
          ${{env.TEST_FILE}}.xml
          assets/style.css

    - name: Pretty print test results
      if: ${{ !cancelled() }}
      uses: pmeier/pytest-results-action@main
      with:
        path: ${{env.TEST_FILE}}.xml
        summary: true
        title: Test results
